### PR TITLE
Undefined.

### PR DESCRIPTION
**Pull request by HideakiAtsuyo**
https://i.imgur.com/VS4NTF3.png => https://i.imgur.com/h8Z6rW3.png

### CODE REVIEW

**Comment by Oocrop** [comment]
This shouldn't happen. Could you tell what your custom status was?

**Comment by HideakiAtsuyo** [comment]
> This shouldn't happen. Could you tell what your custom status was?

You can read on screenshot, but when there is no emote it's Undefined.

**Comment by Oocrop** [comment]
Oh, yeah, I see, but instead of removing the emoji name completely it would be better to add an additional check at line 154

**Comment by HideakiAtsuyo** [comment]
> Oh, yeah, I see, but instead of removing the emoji name completely it would be better to add an additional check at line 154

Why you need the name since if the emoji is detected it will actually show it ? You don't need to see only the name since it will never show it(it's unreachable I'm pretty sure since it show when present but undefined when isn't)

**Comment by Oocrop** [comment]
It's there for default emojis that have the unicode character in the name field

**Comment by HideakiAtsuyo** [comment]
> It's there for default emojis that have the unicode character in the name field

Oh ok I see yeah wait

**Comment by HideakiAtsuyo** [comment]
Now it's better :)

**Pull request merged**
